# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

#WRDUINO_LIBS = Wire


BOARD_TAG    = mega2560
ARDUINO_DIR  = /usr/share/arduino
ARDMK_DIR    = /usr/share/arduino

ARDUINO_LIBS = OneWire PID dht softtimer pcimanager

ARDUINO_PORT = /dev/arduino

PROJECT_DIR       = $(CURDIR)
USER_LIB_PATH    :=  $(PROJECT_DIR)/lib

include /usr/share/arduino/Arduino.mk
